### PR TITLE
Update to Rack API v0.6

### PR DESCRIPTION
**Pull request by cschol**
Update plugin to Rack API v0.6 incl. updated Makefile (reference: [Repair Team)](https://github.com/VCVRack/community/issues/269).

### CODE REVIEW

**Comment by squinkylabs** [comment]
@cschol so I guess you look for branches called 0.6.0dev make pull requests for people? I was planning on keeping my master at 0.5 until 6 comes out. Any reason not to do that? thanks.

**Comment by cschol** [comment]
No. We just provide PRs to help people with the conversion. It is up to you to decide **when** to do the conversion and merge the PR (if you want to). Does that make sense?

**Comment by squinkylabs** [comment]
@cschol totally. tx.

**Comment by cschol** [comment]
`master` is working against `v0.6`. Closing this PR. Thank you!

**Pull request closed without merging**
